# Generated by Django 2.0.2 on 2020-04-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='header',
            field=models.CharField(default='sample header', max_length=255),
        ),
    ]
